In [48]:
import csv
import nltk
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('omw-1.4')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Preprocessing functions
def remove_stopwords(tokens):
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    return filtered_tokens

def lemmatize_tokens(tokens):
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return lemmatized_tokens

# User input
user_input = input("Enter your query: ")

# Preprocess user input
input_tokens = word_tokenize(user_input)
input_tokens = remove_stopwords(input_tokens)
input_tokens = lemmatize_tokens(input_tokens)

# Load CSV data
csv_file = 'video_game_cleaned.csv'  # Replace with your CSV file path
rows = []
with open(csv_file, 'r') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        rows.append(row)

# Preprocess and tokenize CSV data
documents = [' '.join(row) for row in rows]
corpus_tokens = [word_tokenize(doc) for doc in documents]
corpus_tokens = [remove_stopwords(tokens) for tokens in corpus_tokens]
corpus_tokens = [lemmatize_tokens(tokens) for tokens in corpus_tokens]

# Convert tokens back to strings for vectorization
corpus_texts = [' '.join(tokens) for tokens in corpus_tokens]

# Vectorize input and corpus texts
vectorizer = TfidfVectorizer()
vectorized_input = vectorizer.fit_transform([user_input])
vectorized_corpus = vectorizer.transform(corpus_texts)

# Compute cosine similarity between input and corpus
cosine_similarities = cosine_similarity(vectorized_input, vectorized_corpus).flatten()

# Find indices of rows with the highest cosine similarity
top_similar_indices = cosine_similarities.argsort()[::-1]

# Define the number of top matches you want to retrieve
top_matches_count = 1

# Get the top matching rows
top_matching_rows = [rows[i] for i in top_similar_indices[:top_matches_count]]

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/rutgersbootcamp/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rutgersbootcamp/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/rutgersbootcamp/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/rutgersbootcamp/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Enter your query: madden

In [49]:
# Print the top matching rows
print(f"Top {top_matches_count} matching rows:")
for row in top_matching_rows:
    input_video_game = row[1].lower()
    
input_video_game

Top 1 matching rows:

'madden nfl 09'

In [50]:
# Import dependencies
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv('https://raw.githubusercontent.com/mshawn12/video-game-sales-analysis/main/resources/video_game_cleaned.csv')
df.head()

,uniqueid,name,yearreleased,genre,publisher,developer,rating,nasales,eusales,jpsales,othersales,globalsales,criticscore,criticcount,userscore,usercount
0,1,.hack//Infection Part 1,2002,Role-Playing,Atari,CyberConnect2,T,0.49,0.38,0.26,0.13,1.27,75,35,8.5,60
1,2,.hack//Mutation Part 2,2002,Role-Playing,Atari,CyberConnect2,T,0.23,0.18,0.20,0.06,0.68,76,24,8.9,81
2,3,.hack//Outbreak Part 3,2002,Role-Playing,Atari,CyberConnect2,T,0.14,0.11,0.17,0.04,0.46,70,23,8.7,19
3,4,[Prototype],2009,Action,Activision,Radical Entertainment,M,0.84,0.35,0.00,0.12,1.31,78,83,7.8,356
4,5,[Prototype],2009,Action,Activision,Radical Entertainment,M,0.65,0.40,0.00,0.19,1.24,79,53,7.7,308

In [51]:
df = df.drop_duplicates(subset='name')

In [52]:
sample_size = 4420
df = df.sample(n=sample_size, replace=False, random_state=390)

df = df.reset_index()
df = df.drop('index',axis=1)

In [53]:
df.head(50)

,uniqueid,name,yearreleased,genre,publisher,developer,rating,nasales,eusales,jpsales,othersales,globalsales,criticscore,criticcount,userscore,usercount
0,63,Activision Anthology,2002,Misc,Activision,Contraband Entertainment,E,0.25,0.19,0.00,0.06,0.50,75,13,7.7,6
1,2246,Grand Theft Auto: Vice City,2002,Action,Take-Two Interactive,Rockstar North,M,8.41,5.49,0.47,1.78,16.15,95,62,8.7,730
2,2005,Fishing Master,2007,Misc,Konami Digital Entertainment,Hudson Soft,E,0.29,0.00,0.00,0.02,0.31,58,9,8.1,9
3,1933,Fighter Maker 2,2002,Fighting,Enterbrain,Enterbrain,T,0.03,0.03,0.00,0.01,0.07,58,11,7.8,5
4,4772,Romance of the Three Kingdoms X,2005,Strategy,Tecmo Koei,Koei,T,0.04,0.03,0.00,0.01,0.09,71,13,8.5,10
5,1245,Destruction Derby Arenas,2004,Racing,Sony Computer Entertainment,Studio 33,T,0.06,0.05,0.00,0.02,0.13,57,27,7.8,14
6,2390,Hammerin' Hero,2008,Action,Irem Software Engineering,Irem,E10+,0.06,0.00,0.00,0.01,0.07,73,19,7.3,8
7,3346,Metal Gear Solid: Digital Graphic Novel,2006,Misc,Konami Digital Entertainment,Kojima Productions,M,0.02,0.00,0.02,0.00,0.04,78,22,7.2,21
8,1443,Dragon Ball Z: Attack of the Saiyans,2009,Role-Playing,Namco Bandai Games,Monolith Soft,E10+,0.12,0.02,0.21,0.01,0.36,73,21,7.9,24
9,90,Age of Empires III,2005,Strategy,Microsoft Game Studios,Ensemble Studios,T,0.00,0.33,0.00,0.05,0.38,81,52,7.7,519
10,4463,Psi-Ops: The Mindgate Conspiracy,2004,Shooter,Midway Games,Midway,M,0.14,0.11,0.00,0.04,0.29,84,46,8.9,27
11,6316,Total War: Attila,2015,Strategy,Sega,Creative Assembly,T,0.09,0.13,0.00,0.02,0.24,80,66,7.3,520
12,1154,Deadliest Warrior: Ancient Combat,2012,Fighting,Cloud Imperium Games Corporation,"Pipeworks Software, Inc.",M,0.04,0.00,0.00,0.00,0.04,37,5,6.3,4
13,1539,Dungeon Siege II,2005,Role-Playing,Microsoft Game Studios,Gas Powered Games,M,0.00,0.02,0.00,0.00,0.03,80,51,7.9,159
14,2253,Grand Theft Auto IV,2008,Action,Take-Two Interactive,Rockstar North,M,6.76,3.07,0.14,1.03,11.01,98,86,7.9,2951
15,3886,NCAA March Madness 07,2007,Sports,Electronic Arts,EA Canada,E,0.28,0.22,0.00,0.07,0.56,63,9,8.6,7
16,4609,Red Orchestra 2: Heroes of Stalingrad,2011,Shooter,Tripwire Interactive,Tripwire Interactive,M,0.04,0.07,0.00,0.02,0.14,76,49,7.3,729
17,2736,Just Dance 4,2012,Misc,Ubisoft,Ubisoft,E10+,4.05,2.16,0.00,0.55,6.76,74,10,7.3,28
18,4469,Puchi Puchi Virus,2007,Puzzle,Jaleco,Jaleco Entertainment,E,0.07,0.00,0.00,0.01,0.08,73,17,4.2,5
19,1186,Dead Space 2,2011,Shooter,Electronic Arts,Visceral Games,M,0.94,0.44,0.00,0.13,1.51,90,83,8.6,679
20,3658,Napoleon: Total War,2010,Strategy,Sega,Creative Assembly,T,0.02,0.53,0.00,0.12,0.66,81,56,7.9,515
21,4367,Power Rangers: Wild Force,2002,Action,THQ,Natsume,E,0.15,0.05,0.00,0.00,0.21,55,4,6.9,8
22,4077,NieR,2010,Role-Playing,Square Enix,Cavia Inc.,M,0.17,0.18,0.20,0.07,0.61,68,58,8.4,263
23,6188,Tom Clancy's Ghost Recon: Island Thunder,2003,Shooter,Ubisoft,Red Storm Entertainment,M,0.61,0.24,0.00,0.03,0.87,81,33,8.8,17
24,3743,NBA 10: The Inside,2009,Sports,Sony Computer Entertainment,SCEA San Diego Studios,E,0.07,0.00,0.00,0.01,0.08,69,13,3.0,13
25,3239,Marvel Super Hero Squad: The Infinity Gauntlet,2010,Action,THQ,THQ,E10+,0.12,0.02,0.00,0.01,0.15,55,10,6.3,6
26,1097,Darkest of Days,2009,Shooter,Phantom EFX,8Monkey Labs,M,0.09,0.00,0.00,0.01,0.10,44,25,4.8,76
27,6379,Tropico 5,2014,Simulation,Kalypso Media,Haemimont,T,0.02,0.09,0.00,0.01,0.12,75,51,7.0,351
28,2771,Killing Floor 2,2016,Shooter,Tripwire Interactive,Tripwire Interactive,M,0.03,0.01,0.00,0.01,0.05,76,39,8.0,57
29,6808,Xenosaga Episode I: Der Wille zur Macht,2002,Role-Playing,Namco Bandai Games,Monolith Soft,T,0.63,0.49,0.45,0.17,1.74,83,35,8.7,99
30,1335,Disney's Extreme Skate Adventure,2003,Sports,Activision,Toys for Bob,E,0.16,0.12,0.00,0.04,0.32,78,15,8.3,12
31,3784,NBA Ballers,2004,Sports,Midway Games,Midway,E,0.81,0.63,0.00,0.21,1.66,83,44,9.2,19
32,4144,One Piece: Unlimited World Red,2013,Action,Namco Bandai Games,Ganbarion,T,0.05,0.04,0.28,0.01,0.39,75,5,7.6,26
33,6485,Valhalla Knights,2006,Role-Playing,Rising Star Games,K2 LLC,E10+,0.15,0.00,0.07,0.01,0.24,53,29,6.3,15
34,3135,Mafia II,2010,Action,Take-Two Interactive,2K Czech,M,0.85,0.55,0.00,0.15,1.55,74,79,7.8,458
35,1493,Drakengard 2,2005,Role-Playing,Ubisoft,Cavia Inc.,M,0.06,0.05,0.00,0.02,0.13,58,34,5.5,49
36,4533,Rapala Pro Fishing,2004,Sports,Zoo Digital Publishing,Activision,E,0.18,0.14,0.00,0.05,0.36,59,6,8.7,32
37,167,Amplitude,2003,Misc,Sony Computer Entertainment,Harmonix Music Systems,T,0.09,0.07,0.00,0.02,0.18,86,35,8.8,26
38,897,Close Combat: First to Fight,2005,Shooter,Take-Two Interactive,Destineer,T,0.14,0.04,0.00,0.01,0.18,69,46,7.8,10
39,1230,Delta Force: Black Hawk Down,2005,Shooter,NovaLogic,Rebellion,T,0.22,0.17,0.00,0.06,0.46,58,25,8.8,51
40,394,Batman: Dark Tomorrow,2003,Action,Kemco,HotGen,T,0.08,0.02,0.00,0.00,0.11,25,13,3.6,18
41,2,.hack//Mutation Part 2,2002,Role-Playing,Atari,CyberConnect2,T,0.23,0.18,0.20,0.06,0.68,76,24,8.9,81
42,2413,Harry Potter and the Goblet of Fire,2005,Action,Electronic Arts,Electronic Arts,E10+,0.54,0.02,0.00,0.09,0.65,68,29,6.7,48
43,4934,Serious Sam: Next Encounter,2004,Shooter,Global Star,Climax Group,M,0.04,0.03,0.00,0.01,0.07,65,27,7.8,17
44,6671,World's Scariest Police Chases,2001,Racing,Activision,UDS,T,0.20,0.14,0.00,0.02,0.36,54,16,6.3,4
45,1683,ESPN NHL Hockey,2003,Sports,Sega,Kush Games,E,0.11,0.09,0.00,0.03,0.23,90,19,7.0,22
46,430,Battlefield 2: Modern Combat,2005,Shooter,Electronic Arts,Digital Illusions,T,0.39,0.15,0.00,0.02,0.56,80,49,8.2,29
47,3356,Metal Gear Solid 3: Subsistence,2005,Action,Konami Digital Entertainment,Aspect,M,0.34,0.01,0.15,0.06,0.55,94,53,9.3,439
48,882,Clash of the Titans,2010,Action,Namco Bandai Games,Game Republic,T,0.09,0.15,0.01,0.05,0.31,41,28,1.7,17
49,4611,Red Steel 2,2010,Shooter,Ubisoft,Ubisoft Paris,T,0.35,0.20,0.01,0.06,0.62,80,73,8.6,178

In [54]:
def clean_text_pub(publisher):
    result = str(publisher).lower()
    return(result.replace(' ',''))

In [55]:
df['publisher'] = df['publisher'].apply(clean_text_pub)

In [56]:
def clean_text_dev(developer):
    result = str(developer).lower()
    return(result.replace(' ',''))

In [57]:
df['developer'] = df['developer'].apply(clean_text_dev)

In [58]:
df['name'] = df['name'].str.lower()
df['publisher'] = df['publisher'].str.lower()
df['genre'] = df['genre'].str.lower()
df['developer'] = df['developer'].str.lower()

In [59]:
df.columns

Index(['uniqueid', 'name', 'yearreleased', 'genre', 'publisher', 'developer',
       'rating', 'nasales', 'eusales', 'jpsales', 'othersales', 'globalsales',
       'criticscore', 'criticcount', 'userscore', 'usercount'],
      dtype='object')

In [60]:
df2 = df.drop(['nasales', 'eusales', 'jpsales', 'othersales', 'globalsales',
       'criticscore', 'criticcount', 'userscore', 'usercount'],axis=1)

df2['data'] = df2[df2.columns[1:]].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)

In [61]:
vectorizer = CountVectorizer()
vectorized = vectorizer.fit_transform(df2['data'])

In [62]:
similarities = cosine_similarity(vectorized)

In [41]:
# df = pd.DataFrame(similarities)
# df.head(20)

,0,1,2,3,4,5,6,7,8,9,...,4410,4411,4412,4413,4414,4415,4416,4417,4418,4419
0,1.000000,0.111803,0.144338,0.125000,0.000000,0.000000,0.000000,0.111803,0.000000,0.000000,...,0.000000,0.125000,0.133631,0.000000,0.000000,0.000000,0.000000,0.133631,0.000000,0.000000
1,0.111803,1.000000,0.000000,0.111803,0.000000,0.000000,0.119523,0.000000,0.000000,0.000000,...,0.000000,0.111803,0.000000,0.000000,0.000000,0.000000,0.000000,0.119523,0.000000,0.000000
2,0.144338,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.258199,0.000000,0.000000,...,0.000000,0.000000,0.154303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.125000,0.111803,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.125000,0.000000,0.000000,0.000000,0.000000,0.000000,0.133631,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.192450,0.353553,...,0.000000,0.000000,0.000000,0.000000,0.111111,0.000000,0.117851,0.000000,0.000000,0.117851
5,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.133631,0.285714,0.000000,0.125988,0.000000,0.000000,0.142857,0.239046,0.000000
6,0.000000,0.119523,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.109109,0.000000,...,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.111803,0.000000,0.258199,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.119523,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,0.111803
8,0.000000,0.000000,0.000000,0.000000,0.192450,0.000000,0.109109,0.000000,1.000000,0.102062,...,0.000000,0.000000,0.109109,0.204124,0.000000,0.182574,0.102062,0.000000,0.000000,0.204124
9,0.000000,0.000000,0.000000,0.000000,0.353553,0.000000,0.000000,0.000000,0.102062,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.117851,0.000000,0.125000,0.000000,0.000000,0.125000
10,0.000000,0.000000,0.000000,0.000000,0.111111,0.125988,0.000000,0.000000,0.096225,0.000000,...,0.149071,0.000000,0.125988,0.000000,0.000000,0.000000,0.117851,0.000000,0.210819,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.125988,0.000000,0.000000,0.000000,0.000000,0.133631,...,0.169031,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.117851,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.117851,0.000000,0.000000,0.000000,0.204124,0.250000,...,0.000000,0.000000,0.000000,0.250000,0.117851,0.223607,0.000000,0.000000,0.000000,0.375000
14,0.000000,0.737865,0.000000,0.000000,0.000000,0.000000,0.251976,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.144338,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.125000,0.000000,0.335410,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.100504,0.000000,0.000000,0.000000,0.087039,0.106600,...,0.269680,0.000000,0.000000,0.000000,0.000000,0.000000,0.213201,0.000000,0.000000,0.000000
17,0.117851,0.000000,0.136083,0.000000,0.000000,0.000000,0.125988,0.105409,0.096225,0.000000,...,0.000000,0.000000,0.251976,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.136083,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.365148,0.000000,0.000000,0.000000,0.000000,0.000000,0.288675,0.000000,0.129099,0.000000

In [63]:
df = pd.DataFrame(similarities, columns=df['name'], index=df['name']).reset_index()

In [66]:
recommendations = pd.DataFrame(df.nlargest(21,input_video_game)['name'])
recommendations = recommendations[recommendations['name']!=input_video_game]
print('Here are some recommended video games for you from Group 1')
print(recommendations)

Here are some recommended video games for you from Group 1
                         name
2923   madden nfl 09 all-play
3767        nfl head coach 09
145                  nfl tour
341             madden nfl 11
515             madden nfl 12
805             madden nfl 13
1544            madden nfl 08
2565          madden nfl 2005
2888         ncaa football 09
3163            madden nfl 10
3425          madden nfl 2004
4086      madden nfl football
3400  tiger woods pga tour 09
1359               nfl street
3387             nfl street 2
285        ncaa basketball 09
405             madden nfl 25
490           madden nfl 2001
496            fifa soccer 09
809             madden nfl 07

In [68]:
print(similarities)

[[1.         0.1118034  0.14433757 ... 0.13363062 0.         0.        ]
 [0.1118034  1.         0.         ... 0.11952286 0.         0.        ]
 [0.14433757 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.13363062 0.11952286 0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

In [70]:
similarities_df = pd.DataFrame(similarities)

In [77]:
similarity_score = similarities_df.sort_values([0],ascending=False)
similarity_score.head(20)

,0,1,2,3,4,5,6,7,8,9,...,4410,4411,4412,4413,4414,4415,4416,4417,4418,4419
0,1.000000,0.111803,0.144338,0.125000,0.000000,0.0,0.000000,0.111803,0.000000,0.000000,...,0.000000,0.125000,0.133631,0.000000,0.000000,0.000000,0.000000,0.133631,0.000000,0.000000
1620,0.533002,0.000000,0.123091,0.000000,0.201008,0.0,0.113961,0.095346,0.174078,0.213201,...,0.000000,0.000000,0.227921,0.000000,0.100504,0.000000,0.106600,0.000000,0.000000,0.106600
544,0.533002,0.000000,0.123091,0.000000,0.100504,0.0,0.000000,0.095346,0.087039,0.000000,...,0.000000,0.000000,0.113961,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1783,0.533002,0.000000,0.123091,0.000000,0.100504,0.0,0.113961,0.095346,0.174078,0.000000,...,0.134840,0.000000,0.227921,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1853,0.490290,0.000000,0.113228,0.000000,0.000000,0.0,0.209657,0.087706,0.160128,0.000000,...,0.000000,0.000000,0.209657,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3442,0.474342,0.141421,0.000000,0.158114,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.200000,0.158114,0.000000,0.000000,0.000000,0.000000,0.158114,0.169031,0.000000,0.000000
4376,0.474342,0.282843,0.000000,0.158114,0.000000,0.0,0.169031,0.000000,0.000000,0.000000,...,0.000000,0.158114,0.000000,0.000000,0.000000,0.000000,0.000000,0.169031,0.000000,0.000000
4216,0.471405,0.000000,0.000000,0.000000,0.111111,0.0,0.000000,0.000000,0.192450,0.000000,...,0.149071,0.000000,0.000000,0.000000,0.000000,0.000000,0.117851,0.000000,0.000000,0.000000
2475,0.447214,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.141421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000
4188,0.433013,0.000000,0.166667,0.000000,0.000000,0.0,0.154303,0.129099,0.117851,0.000000,...,0.000000,0.000000,0.154303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
187,0.433013,0.129099,0.000000,0.144338,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.144338,0.000000,0.000000,0.000000,0.000000,0.000000,0.154303,0.129099,0.000000
1038,0.433013,0.000000,0.166667,0.000000,0.000000,0.0,0.154303,0.129099,0.000000,0.000000,...,0.000000,0.000000,0.154303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
219,0.433013,0.000000,0.166667,0.000000,0.000000,0.0,0.154303,0.129099,0.117851,0.000000,...,0.000000,0.000000,0.154303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2583,0.433013,0.258199,0.000000,0.144338,0.000000,0.0,0.154303,0.000000,0.000000,0.000000,...,0.000000,0.144338,0.000000,0.000000,0.000000,0.000000,0.000000,0.154303,0.000000,0.000000
1230,0.400892,0.000000,0.154303,0.000000,0.000000,0.0,0.142857,0.119523,0.000000,0.000000,...,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1933,0.400892,0.119523,0.000000,0.267261,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.133631,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000
2219,0.400892,0.000000,0.154303,0.000000,0.000000,0.0,0.142857,0.119523,0.109109,0.000000,...,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3597,0.400892,0.119523,0.000000,0.133631,0.125988,0.0,0.000000,0.000000,0.218218,0.000000,...,0.000000,0.133631,0.000000,0.267261,0.000000,0.239046,0.000000,0.142857,0.000000,0.267261
3321,0.400892,0.000000,0.154303,0.000000,0.000000,0.0,0.285714,0.119523,0.000000,0.000000,...,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
708,0.400892,0.000000,0.154303,0.000000,0.000000,0.0,0.285714,0.119523,0.218218,0.000000,...,0.000000,0.000000,0.285714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [80]:
top_20 = similarity_score.iloc[1:20].mean()
top_20

0       0.448790
1       0.055295
2       0.084196
3       0.052937
4       0.033638
          ...
4415    0.012581
4416    0.020135
4417    0.049073
4418    0.012058
4419    0.019677
Length: 4420, dtype: float64

In [84]:
similarity_score.reset_index()
similarity_score

,0,1,2,3,4,5,6,7,8,9,...,4410,4411,4412,4413,4414,4415,4416,4417,4418,4419
0,1.000000,0.111803,0.144338,0.125,0.000000,0.0,0.000000,0.111803,0.000000,0.000000,...,0.00000,0.125,0.133631,0.00,0.000000,0.000000,0.0000,0.133631,0.000000,0.0000
1620,0.533002,0.000000,0.123091,0.000,0.201008,0.0,0.113961,0.095346,0.174078,0.213201,...,0.00000,0.000,0.227921,0.00,0.100504,0.000000,0.1066,0.000000,0.000000,0.1066
544,0.533002,0.000000,0.123091,0.000,0.100504,0.0,0.000000,0.095346,0.087039,0.000000,...,0.00000,0.000,0.113961,0.00,0.000000,0.000000,0.0000,0.000000,0.000000,0.0000
1783,0.533002,0.000000,0.123091,0.000,0.100504,0.0,0.113961,0.095346,0.174078,0.000000,...,0.13484,0.000,0.227921,0.00,0.000000,0.000000,0.0000,0.000000,0.000000,0.0000
1853,0.490290,0.000000,0.113228,0.000,0.000000,0.0,0.209657,0.087706,0.160128,0.000000,...,0.00000,0.000,0.209657,0.00,0.000000,0.000000,0.0000,0.000000,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1609,0.000000,0.119523,0.000000,0.000,0.000000,0.0,0.142857,0.000000,0.000000,0.000000,...,0.00000,0.000,0.000000,0.00,0.000000,0.000000,0.0000,0.000000,0.000000,0.0000
1610,0.000000,0.119523,0.000000,0.000,0.000000,0.0,0.142857,0.000000,0.000000,0.000000,...,0.00000,0.000,0.000000,0.00,0.251976,0.000000,0.0000,0.000000,0.000000,0.0000
1611,0.000000,0.000000,0.000000,0.000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.000,0.000000,0.00,0.000000,0.000000,0.0000,0.000000,0.111803,0.0000
1612,0.000000,0.000000,0.154303,0.000,0.125988,0.0,0.142857,0.000000,0.109109,0.133631,...,0.00000,0.000,0.142857,0.00,0.000000,0.000000,0.0000,0.000000,0.000000,0.0000
4419,0.000000,0.000000,0.000000,0.000,0.117851,0.0,0.000000,0.111803,0.204124,0.125000,...,0.00000,0.000,0.000000,0.25,0.117851,0.223607,0.0000,0.000000,0.000000,1.0000

In [87]:
c1 = similarity_score[[0]].reset_index()
c1

      index         0
0         0  1.000000
1      1620  0.533002
2       544  0.533002
3      1783  0.533002
4      1853  0.490290
...     ...       ...
4415   1609  0.000000
4416   1610  0.000000
4417   1611  0.000000
4418   1612  0.000000
4419   4419  0.000000

[4420 rows x 2 columns]

In [89]:
top_20 = c1[0].iloc[1:20]
top_20

1     0.533002
2     0.533002
3     0.533002
4     0.490290
5     0.474342
6     0.474342
7     0.471405
8     0.447214
9     0.433013
10    0.433013
11    0.433013
12    0.433013
13    0.433013
14    0.400892
15    0.400892
16    0.400892
17    0.400892
18    0.400892
19    0.400892
Name: 0, dtype: float64

In [90]:
top_20.mean()

0.44879009534352415